
export interface purchase {
    id: string,
    supplierId: string,
    name: string,
    code: string,
    warehouse: string,
    quantity: number,
    payPrice: number,
    totalPrice: number,
    products?: {
        id?: string,
        name: string,
        code: string,
        category: string,
        warehouse: string,
        quantity: number,
        payPrice: number,
        wholesalePrice?: number,
        superWholesalePrice?: number,
        sellPrice: number,
        unit: string,
        alertQuantity?: number,
        lineTotal?: number,
    }[],
    currency: string,
    exchangeRate: number,
    amount_base: number,
    partValue?: number,
    priceCurrency?: "USD",
    paymentCurrency?: "USD" | "SYP",
    totalUSD?: number,
    totalSYP?: number,
    totalOriginal?: number,
    paidUSD?: number,
    paidSYP?: number,
    paidOriginal?: number,
    remainingUSD?: number,
    remainingSYP?: number,
    remainingOriginal?: number,
    paymentStatus: string,
    remainingDebt: number,
        inventoryAccountId: string,
payableAccountId: string,
paymentAccountId?: string,
    date: string,



}
