import type { ProductPriceType } from "./product";

export interface sell {
  id?: string;
  customerId: string;
  totalPrice: number;
  paymentStatus: "cash" | "part" | "debt";
  remainingDebt: number;
  paymentAccountId?: string;
  receivableAccountId?: string;
  salesAccountId?: string;
  currency: string;
  exchangeRate: number;
  amount_base: number;
  priceCurrency?: "USD";
  paymentCurrency?: "USD" | "SYP";
  subtotalUSD?: number;
  totalUSD?: number;
  totalSYP?: number;
  totalOriginal?: number;
  paidUSD?: number;
  paidSYP?: number;
  paidOriginal?: number;
  remainingUSD?: number;
  remainingSYP?: number;
  remainingOriginal?: number;
  discountType?: "none" | "amount" | "percent" | "mixed";
  discountPercent?: number;
  discountPercentUSD?: number;
  discountAmountUSD?: number;
  discountUSD?: number;
  discountSYP?: number;
  discountOriginal?: number;
  products: {
    category: string;
    code: string;
    id: string;
    name: string;
    payPrice: number;
    quantity: number;
    wholesalePrice?: number;
    superWholesalePrice?: number;
    sellPrice: number;
    selectedPriceType?: ProductPriceType;
    unit: string;
    updatedDate: string;
    warehouse: string;
    qty: number;
  }[];
  date?: string;
  partValue?: number;
  discount?: number;
  vehicleId?: string;
  vehicleName?: string;
  driverId?: string;
  driverName?: string;
  sourceWarehouse?: string;
}
